### ISSUE TITLE
Maven and osgi version conversion

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-externals#11]
@dietzc mentioned in an email, that versions of bundles need be defineable as maven versions (and maven variables containing maven versions). This requires maven variables/properties to be evaluated in the groovy script and then possibly converted into osgi compatible versions.

**Comment by dietzc** [comment]
acutally, then I wonder why its working at the moment.

**Comment by Squareys** [comment]
It generates the poms with vars (${scijava-common.version}) for example. That works, because all poms somewhat have the pom-imagej as a parent

**Comment by Squareys** [comment]
osgi bundle versions are currently put in manually

**Comment by dietzc** [comment]
actually no. I changed that yesterday.

**Comment by Squareys** [comment]
So, since it seems to be working for some reason ("If it aint broken, don't fix it"), shall we close this issue?

**Comment by dietzc** [comment]
Ok: Problem with non-numeric is still there. How to reproduce:

a. generate files
b. in target mvn clean install -Denforcer.skip
c. target/update-site mvn clean install -Denforcer.skip

**Comment by Squareys** [comment]
Alright. I will fit this in sometime in the next few days.

**Comment by dietzc** [comment]
fixed in https://github.com/knime-ip/knip-externals/commit/e584fc915e3e5ebcadc263b6bd0193b621a23a1a

I'm sure there are "nicer" ways to do that, but it works!

**Comment by Squareys** [comment]
One could have done the property resolving during the parsing/information gathering stage, which would have made the changes to the only data containing classes unnecessary.

But as long as it works, I'm happy with it, too. Thank you very much! :+1:
