### ISSUE TITLE
TODOLIST for dependencies

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-externals#3]
There are the current dependencies of the individual KNIP projects:

### knip.scifio

-	[ ] mapdb-1.0.3
-	[x] scifio-0.16.4
-	[ ] scifio-jai-imageio-1.1.0.jar

### knip.io

-	[ ] args4j-2.0.25.jar
-	[ ] formats-api-5.0.3.jar
-	[ ] formats-bsd-5.0.3.jar
-	[ ] formats-common-5.0.3.jar
-	[ ] formats-gpl-5.0.3.jar
-	[ ] jai_imageio-5.0.3.jar
-	[ ] jgoodies-common-1.7.0.jar
-	[ ] jgoodies-forms-1.7.2.jar
-	[ ] joda-time-2.2.jar
-	[ ] JWlz-1.4.0.jar
-	[ ] kryo-2.21-shaded.jar
-	[ ] logback-classic-1.1.1.jar
-	[ ] logback-core-1.1.1.jar
-	[ ] mdbtools-java-5.0.3.jar
-	[ ] metakit-5.0.3.jar
-	[ ] native-lib-loader-2.0.1.jar
-	[ ] netcdf-4.3.19.jar
-	[ ] ome-poi-5.0.3.jar
-	[ ] ome-xml-5.0.3.jar
-	[ ] perf4j-0.9.13.jar
-	[ ] scifio-bf-compat-1.8.4.jar
-	[ ] scifio-cli-0.1.0.jar
-	[ ] scifio-ome-xml-0.9.1.jar
-	[ ] specification-5.0.3.jar
-	[ ] turbojpeg-5.0.3.jar

### knip.core

-	[x] imglib2-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-algorithms-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-algorithms-gpl-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-algorithms-legacy-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-meta-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-ops-2.0.0-knip-SNAPSHOT.jar
-	[x] imglib2-realtransform-2.0.0-knip-SNAPSHOT.jar
-	[x] jama-1.0.3.jar
-	[x] jep-2.4.1.jar
-	[x] log4j-1.2.16.jar
-	[x] mahout-collections-1.0.jar
-	[ ] mines-jtk-20100113.jar
-	[ ] mpicbg-20111128.jar
-	[x] slf4j-api-1.6.4.jar
-	[x] slf4j-log4j12-1.6.4.jar
-	[ ] udunits-4.3.18.jar

### knip.tracking

-	[ ] jama-1.0.2.jar
-	[ ] jgrapht_0.8.3.jar
-	[ ] legacy-imglib1-2.0.0-20130818.134407-7.jar
-	[ ] TrackMate_-2.3.0-SNAPSHOT.jar

### knip.base

-	[ ] jep-2.4.1.jar

### knip.imagej2.core

-	[ ] base64-2.3.8.jar
-	[ ] bcmail-jdk14-138.jar
-	[ ] bcprov-jdk14-138.jar
-	[ ] commons-lang3-3.1.jar
-	[ ] gentyref-1.1.0.jar
-	[ ] ij-1.49b.jar
-	[ ] ij1-patcher-0.9.0.jar
-	[ ] imagej-common-0.7.3.jar
-	[ ] imagej-ops-0.4.0.jar
-	[ ] imagej-plugins-commands-0.2.1.jar
-	[ ] imagej-plugins-tools-0.1.1.jar
-	[ ] imagej-plugins-uploader-ssh-0.1.1.jar
-	[ ] imagej-plugins-uploader-webdav-0.1.1.jar
-	[ ] imagej-ui-awt-0.1.2.jar
-	[ ] imagej-ui-swing-0.4.6.jar
-	[ ] imagej-updater-0.3.7.jar
-	[ ] itext-2.1.5.jar
-	[ ] jama-1.0.3.jar
-	[ ] javassist-3.16.1-GA.jar
-	[ ] jcommon-1.0.17.jar
-	[ ] jdatepicker-1.3.2.jar
-	[ ] jfreechart-1.0.14.jar
-	[ ] jhotdraw-7.6.0.jar
-	[ ] jsch-0.1.49.jar
-	[ ] markdownj-0.3.0-1.0.2b4.jar
-	[ ] minimaven-2.1.2.jar
-	[ ] object-inspector-0.1.jar
-	[ ] rsyntaxtextarea-2.0.4.1.jar
-	[ ] Tubeness2Fragment.jar (nicht ganz sicher warum das dabei ist, es kommt nicht im buildpath vor!)

### knip.imagej1
- [ ] imglib.jar
- [ ] mpicbg-20111128.jar

**Comment by dietzc** [comment]
can be closed
