### ISSUE TITLE
Autogenerate build files

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-externals#9]
Goal is to specify all bundles and other update-site information in one file to then generate all the bundle poms, update-site pom and category.xml from this file.

See [autogen branch](https://github.com/knime-ip/knip-externals/compare/autogen)

Current progress: 
 - [x] Discuss format of the central file
 - [x] Generate bundle poms and their parents for all groups
 - [x] Generate update site pom
 - [x] Generate category.xml
 - [x] Add ability to include separate xml files which contain a bundlegroup
 - [x] Complete update-site.xml (add all bundles etc.)
 - [x] Test whether bundles compile
 - [x] Test whether compiled bundles and update site are usable

**Comment by Squareys** [comment]
@dietzc If you have time, it would be great if you could move some of the bundle poms to the new upate-site.xml file.

**Comment by Squareys** [comment]
I will pass on "Test whether compiled bundles and update site are usable" to you, @dietzc. It seems that #11 is not an issue after all. If this is true, I will merge autogen into master as soon as you "give me green light", that the update site is usable.
Jenkins also builds this now.

**Comment by dietzc** [comment]
great! works! must be improved, but I will open separate issues for each improvement.

**Comment by Squareys** [comment]
Awesome! :)
